### ISSUE TITLE
Source for lat/lng data

### ISSUE THREAD

**Issue by hithomasmorelli** [fryford/eatouttohelpout#1]
I'm working on a fork of this project, and I was trying to update the list of registered establishments using HMRC's latest [data release](https://github.com/hmrc/eat-out-to-help-out-establishments/blob/master/data/participating-establishments/restaurants.csv), but their released CSV file doesn't contain lat/lng data. Would you mind letting me know how   you sourced this data for [restaurants.csv](https://github.com/fryford/eatouttohelpout/blob/master/restaurants.csv) so I can source it for the updated list?
Thanks

**Comment by fryford** [comment]
Hi, just used an online batch postcode to Lan long finder. Bear in mind it won't be fully accurate - will just return the postcode centre not the exact address. And that many establishments will share the same postcode....I manually did some spreadsheet work to move these very slightly so they can be seen.

**Comment by hithomasmorelli** [comment]
Thanks - when I've been adding chain restaurants I've just been using the Google Maps Geocoding API, which works within the free tier for that data. However I've got a feeling that putting 60k rows through it might start to rack up a sum, so I might just keep the current dataset for now! Thanks

**Comment by hithomasmorelli** [comment]
On a separate note, would you accept a PR to this project that extends the map to include various chain restaurants not included in the current dataset?

**Comment by fryford** [comment]
Yeah of course - it's not quite as simple as updating the csv. I'm running some manual scripts to generate the tiles that show the pins.

**Comment by hithomasmorelli** [comment]
From looking at the metadata of the tiles folder, I had a rough idea of the scripts that need to be run. Would you mind taking a look at what I've got listed under Final Steps at hithomasmorelli#5 and let me know if it's missing anything?

**Comment by fryford** [comment]
Yup that looks right to me. One thought was that we could keep the chain restaurants and the "independent" ones in separate layers? Different colour markers perhaps? Or keep them the same style for now and look to distinguish when someone has time.

Might help with caching as well. Each time I regenerated the file I was finding I had to put them in different folders as Github didn't seem to be recognising changes to existing tiles.

**Comment by hithomasmorelli** [comment]
I'll keep the same style for now, purely because of time. Might take a look later though. Also, some of the chain restaurants that I haven't processed will be registered individually, so a different colour wouldn't be uniform for all chains.

Not sure how to fix the caching issue. A quick google suggests that it's [a known problem](https://webapps.stackexchange.com/a/119294)

Side note: The bulk postcodes-to-coordinates site seems to have set all Northern Ireland postcodes to 0 lat 0 lng! Only discovered when running my duplicate checker script to combine all the different files. Will run a new script to geocode NI restaurants to get coordinates for them afterwards.
